### Create
POST localhost:8888/vin
Content-Type: application/json

{
  "vin": "2"
}

### Get
GET localhost:8888/vin/1

### Delete
DELETE localhost:8888/vin/1

### Get Not found
GET localhost:8888/vin/1
